Select * from dept;
select  * from emp;
select * from emp where dept_no=30;
select * from emp where dept_no=3;
select id,name,dept_no from emp where role="Clerk"; 
select dept_no,name from emp where dept_no >=2;
select * from emp where commission > salary;
select * from emp where commission>salary*0.6 ;
select * from emp where commission>salary*0.5;
select name,role,salary from emp where dept_no=2 and salary>2000; 
select * from emp where role ="Sales" and dept_no=3 and salary>1500; 
select * from emp where role in("President","Manager");
select * from emp where role="Manager" and dept_no !=3;
select * from emp where dept_no =1 and (role="Manager" or  role="Clerk" );
select * from emp where role="Manager" or(role="Clerk" and dept_no=3);
select * from emp where(role="Manager" and dept_no=1) or (role="Clerk" and dept_no=3);
select * from emp where(role !="Manager" and role !="Clerk") and salary >=2000;
select * from emp where salary between 10000 and 25000;
select * from emp where role in ("Clerk","Analyst","SalesMan");
select * from emp where role not in ("Clerk","Analyst","SalesMan");
select * from emp where Commission is null;
select * from emp where Commission =0;
select * from emp where commission between null and 100;
select * from emp where commission =null ;
select * from emp where (Salary+Commission)>40000;
select * from emp where name like('I%');
select * from emp where name like('%M');
select * from emp where name like('%M%');
select * from emp where name like('____M');
select * from emp where name like('__r%');
select * from emp where month(HIRED_DATE)='feb';
select day(HIRED_DATE) from emp ;#---check table--------24
Select * from emp where HIRED_DATE in(Select max(HIRED_DATE) from emp );
select * from emp where datediff(curdate(),HIRED_DATE)>=12;
select adddate(HIRED_DATE,interval 12 year) from emp; 
Select * from emp where year(hired_date)=2017 and role="Manage";
select * from emp where name like("%,%");
select * from emp where locate(',',name)>0;
select * from emp where ascii(substring(name,1,1)) between 65 and 90 ;
select rpad(name,15,' ')as Name from emp;
select rpad(name,15,'-')as Name from emp;
select length(name) as Name from emp;
select rpad(name,10," "),lpad(name,10," ") as Name from emp;
select NAME FROM emp where substring(name, 1)!='a' ;
select NAME FROM emp where substring(name, -1)!='r' ;
select substring(name, 1, 3) from emp;
select substring(name, -3, 3) from emp;
select replace (name,"a","e") as name from emp;
select * from emp where position('ar' in NAME) ;
select round(salary,1000) as Salary from emp;
select (salary/30) as Salary from emp;
select NAme,(Salary*0.2) as Bonus from emp where Salary*0.2<=5000;
select NAme,(Salary*0.2) as Bonus from emp where Salary*0.2<=2000;
select * from emp where datediff(curdate(),HIRED_DATE);
select name from emp order by name asc;
select * from emp order by role,salary asc;
select * from emp order by role asc,salary desc;
select * from emp order by role,salary desc;